{
 "title": "Sensoren",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Particulate Sensor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Particle Matter PM10",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "airrohr_sds_p1{sensor_id=\"esp8266-xxx\"}",
     "legendFormat": "PM10"
    }
   ]
  },
  {
   "title": "Max Particle Matter PM10",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(airrohr_sds_p1{sensor_id=\"esp8266-xxx\"})",
     "legendFormat": "PM10"
    }
   ]
  },
  {
   "title": "Avg PM10/24h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "avg_over_time(airrohr_sds_p1{sensor_id=\"esp8266-xxx\"}[24h])",
     "legendFormat": "PM10"
    }
   ]
  },
  {
   "title": "Particle Matter PM2.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "airrohr_sds_p2{sensor_id=\"esp8266-xxx\"}",
     "legendFormat": "PM2.5"
    }
   ]
  },
  {
   "title": "Max Particle Matter PM2.5",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(airrohr_sds_p2{sensor_id=\"esp8266-xxx\"})",
     "legendFormat": "PM2.5"
    }
   ]
  },
  {
   "title": "Avg PM2.5/24h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "avg_over_time(airrohr_sds_p2{sensor_id=\"esp8266-xxx\"}[24h])",
     "legendFormat": "PM2.5"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "airrohr_bme280_humidity{sensor_id=\"esp8266-xxx\"}",
     "legendFormat": "Humidity"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "expr": "airrohr_bme280_pressure{sensor_id=\"esp8266-xxx\"}/100",
     "legendFormat": "Pressure"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "airrohr_bme280_temperature{sensor_id=\"esp8266-xxx\"}",
     "legendFormat": "Temperature"
    }
   ]
  }
 ]
}